export const CITIES = [
  'Madrid',
  'Barcelona',
  'Valencia',
  'Sevilla',
  'Zaragoza',
  'Málaga',
  'Murcia',
  'Palma de Mallorca',
  'Las Palmas de Gran Canaria',
  'Bilbao',
  'Alicante',
  'Córdoba',
  'Valladolid',
  'Vigo',
  'Gijón',
  'L\'Hospitalet de Llobregat',
  'Vitoria-Gasteiz',
  'A Coruña',
  'Elche',
  'Granada',
  'Terrassa',
  'Badalona',
  'Oviedo',
  'Cartagena',
  'Sabadell',
  'Jerez de la Frontera',
  'Móstoles',
  'Santa Cruz de Tenerife',
  'Pamplona',
  'Almería'
].sort();
