export const PROVINCES = [
  "Álava", "Albacete", "Alicante", "Almería", "Asturias", "Ávila", "Badajoz", "Baleares", "Barcelona", "Burgos", "Cáceres", "Cádiz", "Cantabria", "Castellón", "Ciudad Real", "Córdoba", "Cuenca", "Gerona", "Granada", "Guadalajara", "Guipúzcoa", "Huelva", "Huesca", "Jaén", "La Coruña", "La Rioja", "Las Palmas", "León", "Lérida", "Lugo", "Madrid", "Málaga", "Murcia", "Navarra", "Orense", "Palencia", "Pontevedra", "Salamanca", "Santa Cruz de Tenerife", "Segovia", "Sevilla", "Soria", "Tarragona", "Teruel", "Toledo", "Valencia", "Valladolid", "Vizcaya", "Zamora", "Zaragoza"
].sort();

export const CITIES_BY_PROVINCE: Record<string, string[]> = {
  "Álava": ["Vitoria-Gasteiz", "Llodio", "Amurrio"],
  "Albacete": ["Albacete", "Hellín", "Villarrobledo", "Almansa"],
  "Alicante": ["Alicante", "Elche", "Torrevieja", "Orihuela", "Benidorm", "Alcoy", "Elda"],
  "Almería": ["Almería", "Roquetas de Mar", "El Ejido", "Níjar", "Adra"],
  "Asturias": ["Gijón", "Oviedo", "Avilés", "Siero", "Langreo"],
  "Ávila": ["Ávila", "Arévalo", "Arenas de San Pedro"],
  "Badajoz": ["Badajoz", "Mérida", "Don Benito", "Almendralejo", "Villanueva de la Serena"],
  "Baleares": ["Palma de Mallorca", "Calvià", "Ibiza", "Manacor", "Santa Eulària des Riu"],
  "Barcelona": ["Barcelona", "Hospitalet de Llobregat", "Badalona", "Terrassa", "Sabadell", "Mataró", "Santa Coloma de Gramenet"],
  "Burgos": ["Burgos", "Miranda de Ebro", "Aranda de Duero"],
  "Cáceres": ["Cáceres", "Plasencia", "Navalmoral de la Mata"],
  "Cádiz": ["Jerez de la Frontera", "Algeciras", "Cádiz", "San Fernando", "El Puerto de Santa María", "Chiclana de la Frontera"],
  "Cantabria": ["Santander", "Torrelavega", "Castro-Urdiales", "Camargo"],
  "Castellón": ["Castellón de la Plana", "Vila-real", "Burriana", "Vinaròs"],
  "Ciudad Real": ["Ciudad Real", "Puertollano", "Tomelloso", "Alcázar de San Juan"],
  "Córdoba": ["Córdoba", "Lucena", "Puente Genil", "Montilla"],
  "Cuenca": ["Cuenca", "Tarancón", "Quintanar del Rey"],
  "Gerona": ["Gerona", "Figueras", "Blanes", "Lloret de Mar"],
  "Granada": ["Granada", "Motril", "Almuñécar", "Armilla", "Maracena"],
  "Guadalajara": ["Guadalajara", "Azuqueca de Henares"],
  "Guipúzcoa": ["San Sebastián", "Irún", "Rentería", "Éibar"],
  "Huelva": ["Huelva", "Lepe", "Almonte", "Moguer"],
  "Huesca": ["Huesca", "Barbastro", "Monzón"],
  "Jaén": ["Jaén", "Linares", "Andújar", "Úbeda", "Martos"],
  "La Coruña": ["A Coruña", "Santiago de Compostela", "Ferrol", "Narón", "Oleiros"],
  "La Rioja": ["Logroño", "Calahorra", "Arnedo"],
  "Las Palmas": ["Las Palmas de Gran Canaria", "Telde", "Santa Lucía de Tirajana", "Arrecife"],
  "León": ["León", "Ponferrada", "San Andrés del Rabanedo"],
  "Lérida": ["Lérida", "Balaguer", "Tárrega"],
  "Lugo": ["Lugo", "Monforte de Lemos", "Vivero"],
  "Madrid": ["Madrid", "Móstoles", "Alcalá de Henares", "Fuenlabrada", "Leganés", "Getafe", "Alcorcón", "Torrejón de Ardoz"],
  "Málaga": ["Málaga", "Marbella", "Mijas", "Fuengirola", "Vélez-Málaga", "Estepona", "Torremolinos"],
  "Murcia": ["Murcia", "Cartagena", "Lorca", "Molina de Segura", "Alcantarilla"],
  "Navarra": ["Pamplona", "Tudela", "Barañáin"],
  "Orense": ["Orense", "Carballino", "Verín"],
  "Palencia": ["Palencia", "Aguilar de Campoo"],
  "Pontevedra": ["Vigo", "Pontevedra", "Vilagarcía de Arousa", "Redondela"],
  "Salamanca": ["Salamanca", "Béjar", "Ciudad Rodrigo"],
  "Santa Cruz de Tenerife": ["Santa Cruz de Tenerife", "San Cristóbal de La Laguna", "Arona", "Adeje"],
  "Segovia": ["Segovia", "Cuéllar"],
  "Sevilla": ["Sevilla", "Dos Hermanas", "Alcalá de Guadaíra", "Utrera", "Mairena del Aljarafe"],
  "Soria": ["Soria", "Almazán"],
  "Tarragona": ["Tarragona", "Reus", "Tortosa", "Vendrell"],
  "Teruel": ["Teruel", "Alcañiz"],
  "Toledo": ["Toledo", "Talavera de la Reina", "Illescas"],
  "Valencia": ["Valencia", "Torrent", "Gandia", "Paterna", "Sagunto"],
  "Valladolid": ["Valladolid", "Laguna de Duero", "Medina del Campo"],
  "Vizcaya": ["Bilbao", "Baracaldo", "Guecho", "Portugalete", "Santurce"],
  "Zamora": ["Zamora", "Benavente"],
  "Zaragoza": ["Zaragoza", "Calatayud", "Utebo"]
};

export const PROVINCE_BY_PREFIX: Record<string, string> = {
  "01": "Álava",
  "02": "Albacete",
  "03": "Alicante",
  "04": "Almería",
  "05": "Ávila",
  "06": "Badajoz",
  "07": "Baleares",
  "08": "Barcelona",
  "09": "Burgos",
  "10": "Cáceres",
  "11": "Cádiz",
  "12": "Castellón",
  "13": "Ciudad Real",
  "14": "Córdoba",
  "15": "La Coruña",
  "16": "Cuenca",
  "17": "Gerona",
  "18": "Granada",
  "19": "Guadalajara",
  "20": "Guipúzcoa",
  "21": "Huelva",
  "22": "Huesca",
  "23": "Jaén",
  "24": "León",
  "25": "Lérida",
  "26": "La Rioja",
  "27": "Lugo",
  "28": "Madrid",
  "29": "Málaga",
  "30": "Murcia",
  "31": "Navarra",
  "32": "Orense",
  "33": "Asturias",
  "34": "Palencia",
  "35": "Las Palmas",
  "36": "Pontevedra",
  "37": "Salamanca",
  "38": "Santa Cruz de Tenerife",
  "39": "Cantabria",
  "40": "Segovia",
  "41": "Sevilla",
  "42": "Soria",
  "43": "Tarragona",
  "44": "Teruel",
  "45": "Toledo",
  "46": "Valencia",
  "47": "Valladolid",
  "48": "Vizcaya",
  "49": "Zamora",
  "50": "Zaragoza",
  "51": "Ceuta",
  "52": "Melilla"
};
